### ISSUE TITLE
macOS  v1.0.0, panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/tlsx#134]
macOS  v1.0.0

tlsx -u www.sina.com.cn -p 443 -scan-mode auto -ps -scan-all-ips -ip-version 4,6 -so -tls-version -cipher -hash sha1 -jarm -ja3 -wildcard-cert -probe-status -expired -self-signed -c 300

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x495ff4e]

goroutine 50 [running]:
github.com/projectdiscovery/tlsx/pkg/output.(*StandardWriter).formatStandard(0xc00070b830, 0xc001198120)
	/Users/51pwn/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.0/pkg/output/output.go:159 +0x5ee
github.com/projectdiscovery/tlsx/pkg/output.(*StandardWriter).Write(0xc00070b830, 0x4c5b919?)
	/Users/51pwn/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.0/pkg/output/output.go:64 +0x59
github.com/projectdiscovery/tlsx/internal/runner.(*Runner).processInputElementWorker(0xc00004f640, 0x0?, 0x0?)
	/Users/51pwn/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.0/internal/runner/runner.go:166 +0x825
created by github.com/projectdiscovery/tlsx/internal/runner.(*Runner).Execute
	/Users/51pwn/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.0/internal/runner/runner.go:122 +0x65
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x495ff4e]

goroutine 58 [running]:
github.com/projectdiscovery/tlsx/pkg/output.(*StandardWriter).formatStandard(0xc00070b830, 0xc0000f6c60)
	/Users/51pwn/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.0/pkg/output/output.go:159 +0x5ee
github.com/projectdiscovery/tlsx/pkg/output.(*StandardWriter).Write(0xc00070b830, 0x4c5b919?)
	/Users/51pwn/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.0/pkg/output/output.go:64 +0x59
github.com/projectdiscovery/tlsx/internal/runner.(*Runner).processInputElementWorker(0xc00004f640, 0x0?, 0x0?)
	/Users/51pwn/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.0/internal/runner/runner.go:166 +0x825
created by github.com/projectdiscovery/tlsx/internal/runner.(*Runner).Execute
	/Users/51pwn/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.0/internal/runner/runner.go:122 +0x65
```

**Comment by Mzack9999** [comment]
@hktalent It works for me, are you able to reproduce this with the `dev` branch?
```console
$ go run . -u www.sina.com.cn -probe-status -self-signed
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\  v1.0.0

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
www.sina.com.cn:443 [success]
[INF] Connections made using crypto/tls: 1, zcrypto/tls: 0, openssl: 0
```

**Comment by hktalent** [comment]
@Mzack9999 
go install github.com/projectdiscovery/tlsx/cmd/tlsx@latest
