### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/tlsx#232]
### tlsx version:
dev | main

### Current Behavior:

```console
echo 34.107.18.135 | ./tlsx
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.0.6

		projectdiscovery.io

[INF] Current tlsx version v1.0.6 (latest)
[INF] Connections made using crypto/tls: 0, zcrypto/tls: 0, openssl: 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x100a6e1fe]

goroutine 83 [running]:
github.com/projectdiscovery/tlsx/pkg/tlsx/openssl.getResponse({0x100ed44a0, 0xc00049f050}, 0xc000572ae0)
	/Users/geekboy/Github/tlsx/pkg/tlsx/openssl/openssl_exec.go:101 +0x59e
github.com/projectdiscovery/tlsx/pkg/tlsx/openssl.(*Client).ConnectWithOptions(0xc0000364b0, {0xc0001e79c0, 0xd}, {0x0?, 0x0?}, {0x100c18799, 0x3}, {{0x0, 0x0}, {0x0, ...}, ...})
	/Users/geekboy/Github/tlsx/pkg/tlsx/openssl/openssl.go:72 +0x3f5
github.com/projectdiscovery/tlsx/pkg/tlsx/auto.(*Client).ConnectWithOptions(0xc00038c048, {0xc0001e79c0, 0xd}, {0x0, 0x0}, {0x100c18799, 0x3}, {{0x0, 0x0}, {0x0, ...}, ...})
	/Users/geekboy/Github/tlsx/pkg/tlsx/auto/auto.go:56 +0x245
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).ConnectWithOptions(0xc00038c000, {0xc0001e79c0, 0xd}, {0x0, 0x0}, {0x100c18799, 0x3}, {{0x0, 0x0}, {0x0, ...}, ...})
	/Users/geekboy/Github/tlsx/pkg/tlsx/tlsx.go:74 +0x243
github.com/projectdiscovery/tlsx/internal/runner.(*Runner).processInputElementWorker(0xc00031b080, 0x0?, 0x0?)
	/Users/geekboy/Github/tlsx/internal/runner/runner.go:179 +0x418
created by github.com/projectdiscovery/tlsx/internal/runner.(*Runner).Execute
	/Users/geekboy/Github/tlsx/internal/runner/runner.go:140 +0x65
```

### Expected Behavior:
parsing cert without crash

### Steps To Reproduce:
```
echo 34.107.18.135 | tlsx
```

### Anything else:
https://github.com/projectdiscovery/httpx/issues/1079

**Comment by ehsandeep** [comment]
with curl:

```console
curl -k https://34.107.18.135:443  -v
*   Trying 34.107.18.135:443...
* Connected to 34.107.18.135 (34.107.18.135) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: C=US; ST=New York; O=Symantec Corporation; emailAddress=DL-FG-Support@symantec.com; CN=itechscout.prod.fire.glass; OU=Web Isolation
*  start date: Aug  7 23:31:07 2022 GMT
*  expire date: Aug  7 23:31:07 2023 GMT
*  issuer: CN=itechscout.prod.fire.glass; C=US; ST=New York; O=Symantec Corporation; OU=Web Isolation; emailAddress=DL-FG-Support@symantec.com
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
> GET / HTTP/1.1
> Host: 34.107.18.135
> User-Agent: curl/7.86.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Sat, 08 Apr 2023 12:46:36 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 139
< Connection: keep-alive
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< Vary: Accept-Encoding
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /</pre>
</body>
</html>
```
